version: '3.8'

services:
  web:
    image: your-dockerhub-username/your-app-image:latest
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    ports:
      - "4000:4000"
    networks:
      - app-network
    environment:
      FLASK_ENV: development
      DATABASE_URL: postgres://user:password@db:5432/appdb
    volumes:
      - web-data:/app

  db:
    image: postgres:13
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: overlay

volumes:
  web-data:
  db-data: